spring.application.name=valore-backend
spring.datasource.url=jdbc:h2:mem:valoredb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

application.security.jwt.secret-key=valore-backend-secret-key-for-phase-two-authentication
application.security.jwt.expiration=86400000
